spring:
  datasource:
    url: jdbc:mysql://boraver.mysql.dbaas.com.br:3306/boraver?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: boraver
    password: W@e3r4t5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
app:
  security:
    jwt-secret: 8782028c-93e4-4664-97b1-c1a3c1780032
    jwt-expiration-ms: 86400000